const defaultShops=[{id:'2252',name:'EDEKA Frauen Heide',status:'Gelb',focus:'Umsatz schwankt, Wareneinsatz beobachten'},{id:'2907',name:'EDEKA Husum',status:'Gelb',focus:'Verwurf senken, starke Produkte pushen'},{id:'4436',name:'REWE Sankt Peter-Ording',status:'Rot',focus:'Umsatz unter Budget, Ursache suchen'},{id:'4499',name:'Famila Husum',status:'Gelb',focus:'Umsatz gut, Verwurf senken'}];
const products=[['California Crunchy Cooked Tuna','California','A','+1 bis +2'],['California Teriyaki Crunch','California','A','+1 bis +2'],['California Lachs Avocado','California','A','+1'],['Happy California Mix','Mix','A','+1'],['Maki Lachs','Maki','A','+1'],['Maki Gurke vegan','Maki','A','+1'],['Sake Box','Mixed Large','A','+1'],['Poké Bowl Lachs','Bowl','B','normal prüfen'],['Wakame Salat vegan','Snack','C','-1 bei Verwurf'],['Ingwer vegan','Snack','C','klein halten'],['Onigiri','Snack','C','-1 bei Verwurf'],['Sommerrolle','Snack','C','später produzieren'],['Blackline/Rainbow Spezial','Premium','C','klein halten']];
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.getElementById(id).classList.remove('hidden')}
function getShops(){return JSON.parse(localStorage.getItem('shops')||JSON.stringify(defaultShops))}
function setShops(s){localStorage.setItem('shops',JSON.stringify(s))}
function renderShops(){const shops=getShops();shopList.innerHTML='';savedShops.innerHTML='';shops.forEach(s=>{const html=`<div class="shop"><b>${s.id} · ${s.name}</b><br><span class="badge ${s.status}">${s.status}</span><p>${s.focus}</p></div>`;shopList.innerHTML+=html;savedShops.innerHTML+=html})}
function addShop(){const shops=getShops();shops.push({id:shopId.value,name:shopName.value,status:shopStatus.value,focus:shopFocus.value});setShops(shops);shopId.value='';shopName.value='';shopFocus.value='';renderShops()}
function renderProducts(){const q=(productSearch.value||'').toLowerCase();productTable.innerHTML='';products.filter(p=>p[0].toLowerCase().includes(q)).forEach(p=>{productTable.innerHTML+=`<tr><td>${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td><td>${p[3]}</td></tr>`})}
function analyze(){const r=Number(revenue.value),b=Number(budget.value),w=Number(waste.value);kpiRevenue.innerText=r+' €';kpiBudget.innerText=b+' €';kpiWaste.innerText=w+' %';let msg='',status='Gelb';if(r>=b&&w<=15){msg='Gut. Umsatz erreicht und Verwurf kontrolliert. Weiter stabil halten.';status='Grün'}else if(r>=b&&w>15){msg='Umsatz gut, aber Verwurf zu hoch. Schwachläufer reduzieren, Bestseller stabil halten.';status='Gelb'}else if(r<b&&w<=10){msg='Umsatz unter Budget, Verwurf niedrig. Bestseller leicht erhöhen und Leerregal prüfen.';status='Gelb'}else{msg='Problem: Umsatz niedrig und Verwurf hoch. Ursache suchen: falsche Produkte, Wetter, Mitarbeiter, Regal oder Planung.';status='Rot'}analysis.innerText=msg;kpiStatus.innerText=status}
function saveVisit(){const v=JSON.parse(localStorage.getItem('visits')||'[]');v.push({shop:visitShop.value,date:visitDate.value,good:visitGood.value,bad:visitBad.value,action:visitAction.value});localStorage.setItem('visits',JSON.stringify(v));visitGood.value='';visitBad.value='';visitAction.value='';renderVisits()}
function renderVisits(){const data=JSON.parse(localStorage.getItem('visits')||'[]');visits.innerHTML='';data.slice().reverse().forEach(v=>{visits.innerHTML+=`<div class="visit"><b>${v.date} · Shop ${v.shop}</b><p><b>Gut:</b> ${v.good}</p><p><b>Problem:</b> ${v.bad}</p><p><b>Maßnahme:</b> ${v.action}</p></div>`})}
function exportData(){const data={shops:getShops(),visits:JSON.parse(localStorage.getItem('visits')||'[]')};alert(JSON.stringify(data,null,2))}
visitDate.valueAsDate=new Date();renderShops();renderProducts();renderVisits();
